# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recomendation.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13recomendation.proto\"!\n\x0eProfileRequest\x12\x0f\n\x07profile\x18\x01 \x03(\x05\"*\n\x0fProfileResponse\x12\x17\n\x0frecommendations\x18\x01 \x03(\t2I\n\x0eProfileService\x12\x37\n\x12GetRecommendations\x12\x0f.ProfileRequest\x1a\x10.ProfileResponseB\x0eZ\x0cprofile.grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recomendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014profile.grpc'
  _globals['_PROFILEREQUEST']._serialized_start=23
  _globals['_PROFILEREQUEST']._serialized_end=56
  _globals['_PROFILERESPONSE']._serialized_start=58
  _globals['_PROFILERESPONSE']._serialized_end=100
  _globals['_PROFILESERVICE']._serialized_start=102
  _globals['_PROFILESERVICE']._serialized_end=175
# @@protoc_insertion_point(module_scope)
